### ISSUE TITLE
Function gg_boxcox relies upon unimported function from MASS

### ISSUE THREAD

**Issue by taylorpospisil** [yeukyul/lindia#1]
The function `gg_boxcox` relies upon the `boxcox` function from MASS.  Since MASS isn't loaded it results in an error.  Should be fixed by adding MASS to the imports in DESCRIPTION.

Example that reproduces: 

```{r}
library(lindia)
model <- lm(Sepal.Length ~ Sepal.Width + Petal.Length + Species, data = iris)
gg_diagnose(model)
```

**Comment by yeukyul** [comment]
Issue fixed in commit b2e63eee54845f2c228b90c038e1a31dad5a1da4
