### ISSUE TITLE
Issue when moderndive package is loaded

### ISSUE THREAD

**Issue by JulieVu** [yeukyul/lindia#11]
Hello, there seems to be a package conflict between lindia and moderndive.

For example, running the following code gives me the error message `Error in if (grepl(" \\* ", term)) { : argument is of length zero` but if I restart R and do not load moderndive, `gg_resX(mod)` works as expected. I also tried this with multiple predictors and in that case, `gg_resX()` will run but will not show the plot for the first predictor entered into the model formula.

```{r}
library(lindia)
library(mosaicData)
library(moderndive)
data("SaratogaHouses")

mod <- lm(price ~ livingArea, data = SaratogaHouses)

gg_resX(mod)
```

**Comment by yeukyul** [comment]
Good catch! Seems like it's a bug that happens when there's only one predictor variable. 

Pushed a fix, and it will go into the next release in the next few days.
