### ISSUE TITLE
Add to list of ggplot2 extension

### ISSUE THREAD

**Issue by Rekyt** [yeukyul/lindia#3]
It would be very cool if `lindia` was added to the list of ggplot2 extensions: https://www.ggplot2-exts.org/gallery/
It would also definitely improve discoverability.

See [here](https://github.com/ggplot2-exts/gallery#adding-a-ggplot2-extension) for the instructions on how to add your package to the list.

**Comment by yeukyul** [comment]
Done. Thanks for the advice! Took me a while to get to it.
